kind: Deployment
apiVersion: apps/v1
metadata:
  name: bd-healthy
  namespace: olmv1-68903-healthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olmv1-dp
  template:
    metadata:
      labels:
        app: olmv1-dp
    spec:
      containers:
      - command:
          - sh
          - -c
          - "sleep 300"
        image: quay.io/openshifttest/hello-openshift:1.2.0
        name: olmv1-dp

