kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: olmv1-ds
  namespace: olmv1-68903-ds-unhealthy
spec:
  selector:
    matchLabels:
      app: olmv1ds
  template:
    metadata:
      labels:
        app: olmv1ds
    spec:
      containers:
      - name: olmv1ds
        command:
          - sh
          - -c
          - "sleep 300"
        imagePullPolicy: IfNotPresent
        image: quay.io/olmqe/hello-openshift:1.2.0no

