apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: olmv1-rs
  namespace: olmv1-68903-rs-unhealthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olmv1-rs
  template:
    metadata:
      labels:
        app: olmv1-rs
    spec:
      serviceAccountName: olmv1-rs
      containers:
      - name: olmv1-rs
        image: quay.io/openshifttest/nginx-alpine:latest
