# permissions for end users to edit ok11399s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ok11399-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-ok1-1399
    app.kubernetes.io/part-of: nginx-ok1-1399
    app.kubernetes.io/managed-by: kustomize
  name: ok11399-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ok11399s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ok11399s/status
  verbs:
  - get
