kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: bd-unhealthy
  namespace: olmv1-bd-unhealthy
spec:
  selector:
    matchLabels:
      app: bd-unhealthy
  template:
    metadata:
      labels:
        app: bd-unhealthy
    spec:
      containers:
      - name: bd-unhealthy
        command:
          - sh
          - -c
          - "sleep 300"
        imagePullPolicy: IfNotPresent
        image: quay.io/olmqe/hello-openshift:1.2.0no
