apiVersion: v1
kind: Pod
metadata:
  labels:
    olmv1: hello-openshift
  name: hello-openshift
  namespace: olmv1-violates
spec:
  containers:
  - command:
      - sh
      - -c
      - "sleep 1800"
    image: quay.io/olmqe/hello-openshift:1.2.0
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop: ["ALL"]
        privileged: false
      seccompProfile:
        type: RuntimeDefault
    name: hello-openshift

