# permissions for end users to edit openv1caseids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openv1caseid-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hello-openshift-bundle
    app.kubernetes.io/part-of: hello-openshift-bundle
    app.kubernetes.io/managed-by: kustomize
  name: openv1caseid-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - openv1caseids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - openv1caseids/status
  verbs:
  - get
