# permissions for end users to view ok21399s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ok21399-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-ok2-1399
    app.kubernetes.io/part-of: nginx-ok2-1399
    app.kubernetes.io/managed-by: kustomize
  name: ok21399-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ok21399s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ok21399s/status
  verbs:
  - get
