apiVersion: cache.example.com/v1alpha1
kind: Okv1test
metadata:
  labels:
    app.kubernetes.io/name: okv1test
    app.kubernetes.io/instance: okv1test-sample
    app.kubernetes.io/part-of: nginx-ok-v1test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nginx-ok-v1test
  name: okv1test-sample
spec:
  # TODO(user): Add fields here
