# permissions for end users to edit okv1tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: okv1test-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-ok-v1test
    app.kubernetes.io/part-of: nginx-ok-v1test
    app.kubernetes.io/managed-by: kustomize
  name: okv1test-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - okv1tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - okv1tests/status
  verbs:
  - get
