# permissions for end users to view okv32777gvks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: okv32777gvk-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-ok-v32777-gvk
    app.kubernetes.io/part-of: nginx-ok-v32777-gvk
    app.kubernetes.io/managed-by: kustomize
  name: okv32777gvk-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - okv32777gvks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - okv32777gvks/status
  verbs:
  - get
