apiVersion: v1
kind: Pod
metadata:
  labels:
    olmv1: hello-openshift
  name: hello-68903
  namespace: olmv1-68903-pod-unhealthy
spec:
  containers:
  - name: hello-68903
    image: quay.io/openshifttest/nginx-alpine:latest.notexisting
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        privileged: false
      seccompProfile:
        type: RuntimeDefault
