apiVersion: v1
kind: Pod
metadata:
  labels:
    olmv1: bd-healthy
  name: bd-healthy
  namespace: olmv1-68903-healthy
spec:
  containers:
  - command:
      - sh
      - -c
      - "sleep 1800"
    image: quay.io/olmqe/hello-openshift:1.2.0
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        privileged: false
      seccompProfile:
        type: RuntimeDefault
    name: bd-healthy
