apiVersion: v1
kind: Pod
metadata:
  labels:
    olmv1: bd-healthy
  name: bd-healthy
  namespace: olmv1-68903-healthy
spec:
  containers:
  - image: quay.io/openshifttest/nginx-alpine:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        privileged: false
      seccompProfile:
        type: RuntimeDefault
    name: bd-healthy
