kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: bd-healthy
  namespace: olmv1-68903-healthy
spec:
  selector:
    matchLabels:
      app: bd-healthy
  template:
    metadata:
      labels:
        app: bd-healthy
    spec:
      containers:
      - name: bd-healthy
        imagePullPolicy: IfNotPresent
        image: quay.io/openshifttest/nginx-alpine:latest
