apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: olmv1-rc
  name: bd-healthy
  namespace: olmv1-68903-healthy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: olmv1-rc
    spec:
      containers:
      - name: olmv1-rc
        image: quay.io/openshifttest/nginx-alpine:latest
