kind: Deployment
apiVersion: apps/v1
metadata:
  name: bd-healthy
  namespace: olmv1-68903-healthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olmv1-dp
  template:
    metadata:
      labels:
        app: olmv1-dp
    spec:
      containers:
      - name: olmv1-dp
        image: quay.io/openshifttest/nginx-alpine:latest

